version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: always
    mem_limit: "1gb"
    mem_reservation: "512m"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog_book_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  server:
    build: ./server
    container_name: flask_server
    restart: always
    mem_limit: "1gb"
    mem_reservation: "512m"
    depends_on:
      - db
    environment:
      FLASK_APP: server
      ENVIRONMENT: dev
      FLASK_DEBUG: "True"
      FLASK_RUN_PORT: 3002
      FLASK_RUN_HOST: "0.0.0.0"
      API_PREFIX: "/api"
      SQLALCHEMY_TRACK_MODIFICATIONS: "True"
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:postgres@postgres_db:5432/catalog_book_db"
      INITIAL_DATABASE_LOAD: "True"
    ports:
      - "3002:3002"
    volumes:
      - .:/code
  client:
    build: ./client
    depends_on:
      - server
    mem_limit: "1gb"
    mem_reservation: "512m"
    container_name: react_client
    working_dir: /home/app
    environment:
      VITE_SERVER_HOST: "http://localhost:3002/api"
    ports:
      - 3006:3006
volumes:
  db:
    driver: local
